### ISSUE TITLE
Version 4.1.3 introduces a compilation error in my project

### ISSUE THREAD

**Issue by wkuranowski** [spotify/futures-extra#38]
Hello,

I upgraded from 4.1.2 to 4.1.3 and received the following error during compilation of my project:

> Error:(218, 47) java: cannot access com.google.api.core.ApiFuture
>   class file for com.google.api.core.ApiFuture not found

Error occurs on this line:
`CompletableFuturesExtra.toCompletableFuture(listenableFuture)`

I am using OpenJDK 11.

Do you need more info?

**Comment by spkrka** [comment]
That is enough for me to reproduce it.

There are two versions of `CompletableFuturesExtra.toCompletableFuture(..)`, one takes an `ApiFuture` and the other takes a `ListenableFuture`.

If you add this dependency the problem goes away:
```
    <dependency>
      <groupId>com.google.api</groupId>
      <artifactId>api-common</artifactId>
      <version>1.7.0</version>
      <scope>provided</scope><!-- so only used for compilation to work, not needed at runtime -->
    </dependency>
```

It seems like the jdk11 compiler is more strict. If you have an overloaded method name, all variants need to be available for it to know what to do.

We should probably stop using overloaded methods for optional dependencies.
Does anyone else have any thoughts on this?

**Comment by wkuranowski** [comment]
Adding this dependency solves the problem. In my opinion, a minor version change (4.1.2 -> 4.1.3) should not cause such confusion. I hope you can find a better solution :)

**Comment by spkrka** [comment]
Do you have any ideas how was introduced @TheIndifferent ? Related to the module-info changes?

A solution could possibly be to deprecate this method and create new methods without overloaded names

**Comment by spkrka** [comment]
Proposed fixl: #39

**Comment by spkrka** [comment]
Try version 4.2.0 (and don't use the deprecated methods)

**Comment by wkuranowski** [comment]
Works fine!
