### ISSUE TITLE
v4.3.2 breaks compatibility with Java 8

### ISSUE THREAD

**Issue by bestbeforetoday** [spotify/futures-extra#58]
```
bad class file: /home/runner/.m2/repository/com/spotify/futures-extra/4.3.2/futures-extra-4.3.2.jar(com/spotify/futures/ListenableFuturesExtra.class)
    class file has wrong version 55.0, should be 52.0
```

**Comment by caesar-ralf** [comment]
That was a mistake, fixed the compatiblity version. Next release https://github.com/spotify/futures-extra/releases/tag/v4.3.3 should be in maven central tomorrow. Thanks for raising the issue @bestbeforetoday
